# Generated by Django 6.1 on 2026-08-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Kessler & Hyde', max_length=200)),
                ('hero_description', models.TextField(default='Timeless Leather, Made to Last.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('hero_cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('hero_cta_link', models.CharField(default='/', max_length=200)),
                ('announcement_text', models.CharField(blank=True, max_length=255)),
                ('leather_quality_section', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage Content',
            },
        ),
    ]
