# Generated by Django 6.1 on 2026-08-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_shipping_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('delivery_min_days', models.PositiveIntegerField(default=3)),
                ('delivery_max_days', models.PositiveIntegerField(default=5)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('return_window_days', models.PositiveIntegerField(default=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
